### ISSUE TITLE
path at the left shows always `/_debug_toolbar/sse` when running with uwsgi

### ISSUE THREAD

**Issue by mei-li** [Pylons/pyramid_debugtoolbar#363] opened 2020-08-26 15:14 UTC
# Description
When we run the application with uwsgi, we see at the left this path instead of the request path
![Screenshot from 2020-08-26 17-09-42](https://user-images.githubusercontent.com/1010264/91321624-1e385700-e7bf-11ea-9c6c-a0b66274fd7c.png)

# Reproduce
steps in this repository can reproduce the issue https://github.com/mei-li/pyramid_scaffold

# Solution
We managed to get it working by storing the path in `DebugToolbar.__init__` because taking it from the request afterwards seems to have overridden the path information.

**Comment by mmerickel** [comment] 2020-08-26 16:52
The issue is that uwsgi, by default, reuses the wsgi environ between requests and mutates it as the minor-est of minor optimizations. The toolbar hangs onto the environ info to display things, and it ends up hanging onto a bunch of references to the same mutable environ.

See https://uwsgi-docs.readthedocs.io/en/latest/articles/WSGIEnvBehaviour.html

This is fixed by setting `wsgi-env-behavior = holy` in your `[uwsgi]` config (which will become the default when uwsgi 2.1 is released).

**Closed by mmerickel** 2020-08-26 16:52 UTC

**Comment by mmerickel** [comment] 2020-08-26 16:53
On a side note, thanks a ton for the reproducible example. Really appreciated.

**Comment by mei-li** [comment] 2020-08-27 09:07
Thank you for this! It worked great
