### ISSUE TITLE
BeforeRender template variables are not displayed in debug toolbar

### ISSUE THREAD

**Issue by domenkozar** [Pylons/pyramid_debugtoolbar#47] opened 2011-11-30 19:59 UTC
One would expect "Renderings" to include such variables under "System Values" or completely another section.

**Comment by mmerickel** [comment] 2015-09-16 00:50
This should no longer be an issue as the toolbar's BeforeRender subscriber is in a separate pyramid app now.

**Comment by bertjwregeer** [comment] 2015-09-16 16:24
I am not sure that this is no longer an issue...

I think what @domenkozar was talking about is that his application has a BeforeRender subscriber, and he adds new variables other than the existing Pyramid system variables, however they are not being captured by the Pyramid debugtoolbar.

Unless the debugtoolbar now captures the data being sent to a renderer in a way other than using a BeforeRender subscriber, this will still be the case as the custom BeforeRender that adds extra values to the renderer may be executed AFTER debugtoolbar has captured the variables.

**Comment by mmerickel** [comment] 2015-09-16 16:31
You're right, thanks for double-checking.

I have no idea how we would solve this without monkey patching the `RendererHelper` or something.

**Comment by jvanasco** [comment] 2016-01-21 18:04
I ran into this issue recently too - I have a BeforeRender that populates the templating space with some constants and helper functions, and needed to support them on my custom panels.

Since I use custom panels, my fix was to use a factory to generate the `data` dict (which pre-populates the namespace).

An approach I thought of taking though, was to have an `environment.ini` config option that will take a a dotted namepace for events (such as BeforeRender) and then register them into the app.  

example:

    debugtoolbar.events.BeforeRender = myapp.events.BeforeRender_a myapp.events.BeforeRender_b

**Comment by mmerickel** [comment] 2016-01-21 18:12
@jvanasco I have no idea what you just said but my first impression is that you may want a custom `BeforeRender` subscribed for your panel template?

**Comment by jvanasco** [comment] 2016-01-21 18:23
rephrased: If I understand correctly, the OP's problem would be solved by using an .ini option to subscribe BeforeRender events onto panel templates.

I solved my variation by replacing:

     self.data = {'request', request... }

with

     self.data = custom_dictionary_factory()
     self.data['request']= request
     ...

**Comment by mmerickel** [comment] 2016-01-21 18:57
Okay, I don't think you understand the original issue correctly.

The issue is the debug toolbar registers a `BeforeRender` subscriber on the parent application in order to capture data and display it on the panel. The subscribers have an ordering and each one is mutating the `event` dictionary adding its values. Thus, the toolbar's subscriber only knows about the state of the dictionary when it's invoked and any subscribers invoked afterward do not show up in the dictionary and thus are missing from the panel.

**Comment by jvanasco** [comment] 2016-01-21 19:33
I thought the renderers no longer run on the debugtoolbar panel because it's now in a separate app (per the Sep 15, 2015 comment above).

**Comment by mmerickel** [comment] 2016-01-21 19:57
You're missing the point. The toolbar registers a before render subscriber on the parent application as a way to figure out what variables were passed to the parent application's templates.

**Comment by domenkozar** [comment] 2016-12-07 10:09
We'd essentially have to implement a sort for `BeforeRender` subscriber to be able to say debug_toolbar comes last.

**Comment by mmerickel** [comment] 2016-12-07 16:15
This is possible to do, but requires some hairy, internal, private hacking of the subscriber order in the registry which is controlled by zope.interface. To do it properly it'd be done in a ApplicationCreated event probably. The code would have to search for the subscriber, remove it, and re-add it to ensure it's last in the order. Alternatively it could just register itself directly into the registry instead of using `config.add_subscriber`.

**Comment by mmerickel** [comment] 2017-04-21 06:27
Closed via #284.

**Closed by mmerickel** 2017-04-21 06:27 UTC
Labels: bug, sprintable
