### ISSUE TITLE
Can't interact with traceback due to application reset

### ISSUE THREAD

**Issue by tflorac** [Pylons/pyramid_debugtoolbar#317] opened 2017-06-14 11:27 UTC
Hi,
I'm trying to use release 4.1 of debug toolbar with Pyramid 1.8.3.
When I'm in history and try to interact in the traceback panel of an exception, I receive an error : "Warning: The request has been lost due to an application reset."
Should I use an older release of DebugToolbar with this version of Pyramid?
Best regards,
Thierry

**Comment by tflorac** [comment] 2017-06-14 14:18
I moved back to release 4.0.1 and everything seems OK.
Is it a "normal" behaviour for Pyramid's release previous to 1.9?

**Comment by bertjwregeer** [comment] 2017-06-14 19:14
> "Warning: The request has been lost due to an application reset."

This means your application was likely restarted, are you using `--reload` with `pserve`?

Changing the version of the debugtoolbar won't make a difference if the debug traceback no longer exists in memory due to a restart.

**Comment by mmerickel** [comment] 2017-06-14 19:28
@tflorac can you confirm that this bug occurs without restarting the server? You simply cannot view the traceback panel for an exception that just occurred?

**Comment by tflorac** [comment] 2017-06-15 11:47
@mmerickel : no, of course the bug occurs without restarting the server.
@bertjwregeer : I don't use the "--reload" option of pserve.
The problem doesn't occur when I display the traceback panel but when I try to interact with it, for example when I try to use the interpreter on any step of the stacktrace.
Actually, switching to release 4.0.1 of DebugToolbar package solved the problem...

**Comment by mmerickel** [comment] 2017-06-15 15:24
@tflorac Thanks, I'll try to look at this soon.

**Comment by jensens** [comment] 2017-06-17 07:07
I found the same problem. I created a minimal example to reproduce it https://github.com/jensens/reproduce_debug_problem.

Also, the page layout is broken (tested in FF and Chrome) when reset happens:
![screenshot from 2017-06-17 09 05 47](https://user-images.githubusercontent.com/157140/27250958-40fde590-533c-11e7-843e-00b751374f4c.png)

**Comment by mmerickel** [comment] 2017-06-21 06:39
@tflorac @jensens Would you mind testing out the fix-tracebacks branch from https://github.com/Pylons/pyramid_debugtoolbar/pull/318 and see if things are working for you now? This ended up being a pretty major fix.

**Comment by tflorac** [comment] 2017-06-21 09:50
@mmerickel : I checked out your branch and made a quick test this morning. Generating an exception and switching to traceback panel, everything seems to work correctly!!

**Comment by mmerickel** [comment] 2017-06-21 23:50
Fixed via https://github.com/Pylons/pyramid_debugtoolbar/pull/318.

**Closed by mmerickel** 2017-06-21 23:50 UTC
Labels: bug
